import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is required.");
}
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🚀 Adding portfolio projects...");

  // Supprimer les anciens projets pour éviter les doublons
  await prisma.projectTechnology.deleteMany({});
  await prisma.projectChallenge.deleteMany({});
  await prisma.projectSolution.deleteMany({});
  await prisma.projectResult.deleteMany({});
  await prisma.projectGallery.deleteMany({});
  await prisma.project.deleteMany({});
  console.log("🗑️ Old projects deleted");

  const projects = [
    {
      slug: "africa-happy",
      title: "Africa Happy",
      category: "Site Web",
      description: "Plateforme web pour Africa Happy, une entreprise dédiée au bien-être et aux services en Afrique.",
      fullDescription: "Conception et développement d'une plateforme web moderne pour Africa Happy. Le site présente les services de l'entreprise avec une interface conviviale et un design africain authentique.",
      client: "Africa Happy",
      date: "2024",
      image: "/images/projects/Africa Happy.png",
      order: 1,
      isActive: true,
      isFeatured: true,
      technologies: ["WordPress", "Elementor", "CSS"],
      challenges: ["Créer une identité visuelle africaine moderne", "Optimiser pour les connexions lentes"],
      solutions: ["Design inspiré des motifs africains", "Optimisation des images et lazy loading"],
      results: ["Site performant et attractif", "Augmentation de la visibilité en ligne"],
    },
    {
      slug: "agence-securite-aass",
      title: "Agence de Sécurité AASS",
      category: "Site Web",
      description: "Site web professionnel pour une agence de sécurité au Sénégal.",
      fullDescription: "Développement d'un site vitrine pour l'Agence de Sécurité AASS, présentant leurs services de gardiennage, surveillance et protection.",
      client: "AASS",
      date: "2024",
      image: "/images/projects/Agence de Sécurité AASS.png",
      order: 2,
      isActive: true,
      isFeatured: false,
      technologies: ["WordPress", "Elementor"],
      challenges: ["Inspirer confiance et professionnalisme"],
      solutions: ["Design sobre et professionnel", "Mise en avant des certifications"],
      results: ["Image de marque renforcée", "Nouveaux contrats générés"],
    },
    {
      slug: "aruo-service",
      title: "Aruo Service",
      category: "Site Web",
      description: "Site web professionnel pour une entreprise de services.",
      fullDescription: "Conception et développement d'un site web moderne et responsive pour Aruo Service, une entreprise spécialisée dans les services aux professionnels.",
      client: "Aruo Service",
      date: "2025",
      image: "/images/projects/Aruo(site internet).png",
      order: 3,
      isActive: true,
      isFeatured: true,
      technologies: ["WordPress", "Elementor", "PHP"],
      challenges: ["Présenter clairement les services", "Faciliter la prise de contact"],
      solutions: ["Architecture de contenu optimisée", "Formulaires de contact intégrés"],
      results: ["Meilleure visibilité en ligne", "Augmentation des demandes de devis"],
    },
    {
      slug: "elite-science",
      title: "Elite Science",
      category: "Site Web",
      description: "Plateforme éducative pour un centre de formation scientifique.",
      fullDescription: "Développement d'une plateforme web pour Elite Science, un centre de formation proposant des cours de sciences et de mathématiques.",
      client: "Elite Science",
      date: "2025",
      image: "/images/projects/Elite science(site internet).png",
      order: 4,
      isActive: true,
      isFeatured: true,
      technologies: ["WordPress", "LearnDash", "Elementor"],
      challenges: ["Intégrer un système de cours en ligne", "Gérer les inscriptions"],
      solutions: ["Plateforme LMS intégrée", "Système de paiement en ligne"],
      results: ["Augmentation des inscriptions", "Gestion simplifiée des cours"],
    },
    {
      slug: "fabiram-by-amsa",
      title: "Fabiram by Amsa",
      category: "Site Web",
      description: "Site e-commerce pour une marque de mode africaine.",
      fullDescription: "Création d'une boutique en ligne pour Fabiram by Amsa, une marque de vêtements et accessoires inspirés de la culture africaine.",
      client: "Fabiram by Amsa",
      date: "2024",
      image: "/images/projects/Fabiram-by-Amsa.png",
      order: 5,
      isActive: true,
      isFeatured: false,
      technologies: ["WooCommerce", "WordPress", "Stripe"],
      challenges: ["Mettre en valeur les produits", "Intégrer le paiement mobile"],
      solutions: ["Galerie produits haute qualité", "Intégration Wave et Orange Money"],
      results: ["Ventes en ligne lancées", "Clientèle élargie"],
    },
    {
      slug: "gestion-commercial-moultazam",
      title: "Gestion Commercial Moultazam",
      category: "Application Web",
      description: "Application de gestion commerciale pour une entreprise de distribution.",
      fullDescription: "Développement d'une application web de gestion commerciale incluant la facturation, le suivi des stocks et la gestion des clients.",
      client: "Moultazam",
      date: "2024",
      image: "/images/projects/Gestion commercial_Moultazam.png",
      order: 6,
      isActive: true,
      isFeatured: false,
      technologies: ["React", "Node.js", "PostgreSQL", "Express"],
      challenges: ["Automatiser les processus de vente", "Générer des rapports en temps réel"],
      solutions: ["Dashboard interactif", "Système de facturation automatisé"],
      results: ["Gain de temps de 60%", "Meilleur suivi des ventes"],
    },
    {
      slug: "gestion-pharmacies",
      title: "Gestion des Pharmacies",
      category: "Application Web",
      description: "Système de gestion pour pharmacies avec suivi des stocks et des ventes.",
      fullDescription: "Application complète de gestion pharmaceutique permettant le suivi des médicaments, la gestion des stocks, les alertes de péremption et la facturation.",
      client: "Projet Personnel",
      date: "2024",
      image: "/images/projects/Gestion des pharmarcie(github).png",
      order: 7,
      isActive: true,
      isFeatured: false,
      technologies: ["React", "Node.js", "MongoDB"],
      challenges: ["Gérer les dates de péremption", "Assurer la traçabilité"],
      solutions: ["Alertes automatiques", "Historique complet des transactions"],
      results: ["Réduction des pertes", "Conformité réglementaire"],
    },
    {
      slug: "gestion-taches",
      title: "Gestion des Tâches",
      category: "Application Web",
      description: "Application de gestion de tâches et de projets collaboratifs.",
      fullDescription: "Outil de productivité permettant de créer, organiser et suivre des tâches avec fonctionnalités de collaboration en équipe.",
      client: "Projet Personnel",
      date: "2024",
      image: "/images/projects/Gestion des tâches(github).png",
      order: 8,
      isActive: true,
      isFeatured: false,
      technologies: ["React", "Firebase", "TailwindCSS"],
      challenges: ["Interface intuitive", "Synchronisation en temps réel"],
      solutions: ["Drag & drop", "WebSockets pour temps réel"],
      results: ["Productivité améliorée", "Collaboration facilitée"],
    },
    {
      slug: "kerdigit",
      title: "KerDigit",
      category: "Site Web",
      description: "Site web pour une agence digitale basée à Dakar.",
      fullDescription: "Création du site vitrine de KerDigit, une agence spécialisée dans la transformation digitale des entreprises sénégalaises.",
      client: "KerDigit",
      date: "2024",
      image: "/images/projects/KerDigit.png",
      order: 9,
      isActive: true,
      isFeatured: false,
      technologies: ["Next.js", "TailwindCSS", "Framer Motion"],
      challenges: ["Design moderne et innovant", "Performance optimale"],
      solutions: ["Animations fluides", "SSG pour la performance"],
      results: ["Site rapide et attractif", "Bonne image de marque"],
    },
    {
      slug: "khidma-service-digital",
      title: "Khidma Service Digital",
      category: "Site Web",
      description: "Site web pour l'agence Khidma Service Digital.",
      fullDescription: "Développement du site officiel de Khidma Service Digital, présentant les services de communication digitale, développement web et design.",
      client: "Khidma Service Digital",
      date: "2025",
      image: "/images/projects/Khidma Service(site internet).png",
      order: 10,
      isActive: true,
      isFeatured: true,
      technologies: ["Next.js", "React", "TailwindCSS", "PostgreSQL", "Prisma"],
      challenges: ["Site moderne et performant", "Back-office intégré"],
      solutions: ["Architecture Next.js App Router", "API REST complète"],
      results: ["Présence en ligne professionnelle", "Gestion de contenu simplifiée"],
    },
    {
      slug: "new-horizon-hotel",
      title: "New Horizon Hotel",
      category: "Design/Maquette",
      description: "Maquette UI/UX pour un site d'hôtel de luxe.",
      fullDescription: "Conception d'une maquette complète pour le site web de New Horizon Hotel, un établissement hôtelier haut de gamme.",
      client: "New Horizon Hotel",
      date: "2024",
      image: "/images/projects/Maquette New Horizon Hotel.png",
      order: 11,
      isActive: true,
      isFeatured: false,
      technologies: ["Figma", "Adobe XD"],
      challenges: ["Transmettre le luxe et l'élégance", "UX de réservation fluide"],
      solutions: ["Design épuré et sophistiqué", "Parcours de réservation optimisé"],
      results: ["Maquette validée par le client", "Prêt pour le développement"],
    },
    {
      slug: "initiation-wordpress",
      title: "Initiation WordPress",
      category: "Design/Maquette",
      description: "Maquette pour un site de formation WordPress.",
      fullDescription: "Design d'une plateforme de formation en ligne dédiée à l'apprentissage de WordPress pour débutants.",
      client: "Projet Personnel",
      date: "2024",
      image: "/images/projects/Maquette initiation wordpress.png",
      order: 12,
      isActive: true,
      isFeatured: false,
      technologies: ["Figma"],
      challenges: ["Interface pédagogique", "Navigation intuitive"],
      solutions: ["Design clair et structuré", "Progression visuelle des cours"],
      results: ["Concept validé", "Base pour développement futur"],
    },
    {
      slug: "landing-page-monito",
      title: "Landing Page Monito",
      category: "Design/Maquette",
      description: "Maquette d'une landing page pour une animalerie en ligne.",
      fullDescription: "Conception d'une landing page attractive pour Monito, une boutique en ligne spécialisée dans les animaux de compagnie.",
      client: "Monito",
      date: "2024",
      image: "/images/projects/Maquette landing page Monito.png",
      order: 13,
      isActive: true,
      isFeatured: false,
      technologies: ["Figma", "Photoshop"],
      challenges: ["Design ludique et engageant", "Conversion optimisée"],
      solutions: ["Visuels d'animaux attractifs", "CTA bien placés"],
      results: ["Taux de conversion amélioré", "Design approuvé"],
    },
    {
      slug: "moultazam",
      title: "Moultazam",
      category: "Site Web",
      description: "Site web pour une entreprise de distribution alimentaire.",
      fullDescription: "Développement d'un site vitrine pour Moultazam, une entreprise de distribution de produits alimentaires au Sénégal.",
      client: "Moultazam",
      date: "2024",
      image: "/images/projects/Moultazam.png",
      order: 14,
      isActive: true,
      isFeatured: false,
      technologies: ["WordPress", "Elementor"],
      challenges: ["Présenter le catalogue produits", "Faciliter les commandes B2B"],
      solutions: ["Catalogue en ligne", "Formulaire de commande"],
      results: ["Visibilité accrue", "Processus de commande simplifié"],
    },
    {
      slug: "murid-pro",
      title: "Murid Pro",
      category: "Site Web",
      description: "Plateforme communautaire pour la communauté mouride.",
      fullDescription: "Développement d'une plateforme web pour Murid Pro, offrant des ressources et services pour la communauté mouride.",
      client: "Murid Pro",
      date: "2024",
      image: "/images/projects/Murid Pro(site internet).png",
      order: 15,
      isActive: true,
      isFeatured: false,
      technologies: ["WordPress", "BuddyPress", "Elementor"],
      challenges: ["Fonctionnalités communautaires", "Gestion des membres"],
      solutions: ["Espace membre intégré", "Forum de discussion"],
      results: ["Communauté active", "Engagement des membres"],
    },
    {
      slug: "ndayane-services",
      title: "Ndayane Services",
      category: "Site Web",
      description: "Site web pour une entreprise de services à Ndayane.",
      fullDescription: "Création d'un site vitrine pour Ndayane Services, présentant leurs offres de services locaux.",
      client: "Ndayane Services",
      date: "2024",
      image: "/images/projects/Ndayane services.png",
      order: 16,
      isActive: true,
      isFeatured: false,
      technologies: ["Next.js", "TailwindCSS"],
      challenges: ["Design simple et efficace", "Chargement rapide"],
      solutions: ["Site statique optimisé", "Images compressées"],
      results: ["Présence en ligne établie", "Nouveaux clients"],
    },
    {
      slug: "s-and-c",
      title: "S&C",
      category: "Site Web",
      description: "Site web pour une entreprise de conseil et services.",
      fullDescription: "Développement d'un site professionnel pour S&C, une société de conseil aux entreprises.",
      client: "S&C",
      date: "2024",
      image: "/images/projects/S&C(site internet).png",
      order: 17,
      isActive: true,
      isFeatured: false,
      technologies: ["WordPress", "Elementor", "PHP"],
      challenges: ["Image professionnelle", "Génération de leads"],
      solutions: ["Design corporate", "Formulaires de contact optimisés"],
      results: ["Crédibilité renforcée", "Leads qualifiés"],
    },
    {
      slug: "saltis",
      title: "Saltis",
      category: "Site Web",
      description: "Site web pour Saltis, entreprise de solutions technologiques.",
      fullDescription: "Création du site web de Saltis, une entreprise proposant des solutions technologiques innovantes pour les entreprises.",
      client: "Saltis",
      date: "2024",
      image: "/images/projects/Saltis.png",
      order: 18,
      isActive: true,
      isFeatured: true,
      technologies: ["Next.js", "React", "TailwindCSS"],
      challenges: ["Présenter des solutions techniques", "Design moderne"],
      solutions: ["Animations interactives", "Explications visuelles"],
      results: ["Site attractif", "Meilleure compréhension des services"],
    },
    {
      slug: "african-west-technology",
      title: "African West Technology",
      category: "Site Web",
      description: "Site web pour une entreprise technologique ouest-africaine.",
      fullDescription: "Développement du site d'African West Technology, une entreprise spécialisée dans les solutions IT en Afrique de l'Ouest.",
      client: "African West Technology",
      date: "2024",
      image: "/images/projects/african west technology(site internet).png",
      order: 19,
      isActive: true,
      isFeatured: true,
      technologies: ["Next.js", "React", "Node.js", "PostgreSQL"],
      challenges: ["Site multilingue", "Présentation des solutions IT"],
      solutions: ["Internationalisation", "Portfolio interactif"],
      results: ["Expansion régionale", "Nouveaux partenariats"],
    },
    {
      slug: "bibliotheque",
      title: "Bibliothèque",
      category: "Application Web",
      description: "Système de gestion de bibliothèque en ligne.",
      fullDescription: "Application web de gestion de bibliothèque permettant le catalogage des livres, la gestion des emprunts et le suivi des membres.",
      client: "Projet Personnel",
      date: "2024",
      image: "/images/projects/bibliothèque(github).png",
      order: 20,
      isActive: true,
      isFeatured: false,
      technologies: ["React", "Node.js", "MongoDB", "Express"],
      challenges: ["Gestion des emprunts", "Recherche avancée"],
      solutions: ["Système de réservation", "Filtres de recherche"],
      results: ["Gestion simplifiée", "Accès facilité aux ressources"],
    },
    {
      slug: "diapale-pos",
      title: "Diapalé POS",
      category: "Application Web",
      description: "Système de point de vente moderne et intuitif.",
      fullDescription: "Développement d'un système de caisse (POS) complet pour les commerces, avec gestion des stocks, facturation et rapports de ventes.",
      client: "Diapalé",
      date: "2025",
      image: "/images/projects/diapalé(site internet).png",
      order: 21,
      isActive: true,
      isFeatured: true,
      technologies: ["React", "Node.js", "PostgreSQL", "Electron"],
      challenges: ["Interface rapide", "Mode hors-ligne"],
      solutions: ["Cache local", "Synchronisation automatique"],
      results: ["Transactions plus rapides", "Zéro perte de données"],
    },
    {
      slug: "gestion-budget",
      title: "Gestion des Budgets",
      category: "Application Web",
      description: "Application de suivi et gestion de budget personnel.",
      fullDescription: "Outil de gestion financière permettant de suivre ses dépenses, définir des budgets et visualiser ses finances.",
      client: "Projet Personnel",
      date: "2024",
      image: "/images/projects/gestion des budget(github).png",
      order: 22,
      isActive: true,
      isFeatured: false,
      technologies: ["React", "Chart.js", "Firebase"],
      challenges: ["Visualisation des données", "Catégorisation automatique"],
      solutions: ["Graphiques interactifs", "IA pour catégorisation"],
      results: ["Meilleur contrôle financier", "Économies réalisées"],
    },
    {
      slug: "ideatys-digital",
      title: "Ideatys Digital",
      category: "Site Web",
      description: "Site web pour une agence de marketing digital.",
      fullDescription: "Création du site d'Ideatys Digital, une agence spécialisée dans le marketing digital et la communication en ligne.",
      client: "Ideatys Digital",
      date: "2024",
      image: "/images/projects/ideatys digital.png",
      order: 23,
      isActive: true,
      isFeatured: false,
      technologies: ["WordPress", "Elementor", "JavaScript"],
      challenges: ["Montrer l'expertise digitale", "Portfolio attractif"],
      solutions: ["Animations modernes", "Études de cas détaillées"],
      results: ["Image d'expert renforcée", "Nouveaux clients"],
    },
    {
      slug: "maquette-ksd",
      title: "Maquette Khidma Service Digital",
      category: "Design/Maquette",
      description: "Maquette UI/UX pour le site Khidma Service Digital.",
      fullDescription: "Conception de la maquette complète du site KSD, incluant toutes les pages et composants de l'interface.",
      client: "Khidma Service Digital",
      date: "2025",
      image: "/images/projects/maquette khidma service digital.png",
      order: 24,
      isActive: true,
      isFeatured: false,
      technologies: ["Figma", "Adobe Illustrator"],
      challenges: ["Design cohérent", "Expérience utilisateur optimale"],
      solutions: ["Design system complet", "Prototypes interactifs"],
      results: ["Maquette validée", "Développement facilité"],
    },
    {
      slug: "medical-distribution",
      title: "Medical Distribution",
      category: "Site Web",
      description: "Site web pour une entreprise de distribution médicale.",
      fullDescription: "Développement d'un site pour Medical Distribution, une entreprise spécialisée dans la distribution de matériel et produits médicaux.",
      client: "Medical Distribution",
      date: "2024",
      image: "/images/projects/medical distribution.png",
      order: 25,
      isActive: true,
      isFeatured: false,
      technologies: ["WordPress", "WooCommerce", "Elementor"],
      challenges: ["Catalogue produits médical", "Conformité réglementaire"],
      solutions: ["Fiches produits détaillées", "Mentions légales complètes"],
      results: ["Ventes B2B augmentées", "Processus de commande simplifié"],
    },
    {
      slug: "wadude",
      title: "Wadude",
      category: "Site Web",
      description: "Plateforme web pour Wadude.",
      fullDescription: "Création d'une plateforme web moderne pour Wadude, avec des fonctionnalités interactives et un design attrayant.",
      client: "Wadude",
      date: "2024",
      image: "/images/projects/wadude(site internet).png",
      order: 26,
      isActive: true,
      isFeatured: false,
      technologies: ["Next.js", "React", "TailwindCSS"],
      challenges: ["Interface moderne", "Performance optimale"],
      solutions: ["SSR pour la performance", "Design responsive"],
      results: ["Expérience utilisateur améliorée", "Temps de chargement réduit"],
    },
    {
      slug: "waqf",
      title: "Waqf",
      category: "Site Web",
      description: "Plateforme de gestion de waqf (dotations islamiques).",
      fullDescription: "Développement d'une plateforme complète pour la gestion des waqf, incluant les dons, le suivi des projets et les rapports.",
      client: "Waqf Foundation",
      date: "2024",
      image: "/images/projects/waqf.png",
      order: 27,
      isActive: true,
      isFeatured: true,
      technologies: ["Next.js", "React", "Node.js", "PostgreSQL"],
      challenges: ["Gestion des dons", "Transparence des fonds"],
      solutions: ["Tableau de bord donateurs", "Rapports automatisés"],
      results: ["Confiance des donateurs", "Gestion transparente"],
    },
  ];

  for (const projectData of projects) {
    const { technologies, challenges, solutions, results, ...project } = projectData;

    const createdProject = await prisma.project.create({
      data: project,
    });

    // Add technologies
    for (let i = 0; i < technologies.length; i++) {
      await prisma.projectTechnology.create({
        data: {
          name: technologies[i],
          order: i,
          projectId: createdProject.id,
        },
      });
    }

    // Add challenges
    for (let i = 0; i < challenges.length; i++) {
      await prisma.projectChallenge.create({
        data: {
          text: challenges[i],
          order: i,
          projectId: createdProject.id,
        },
      });
    }

    // Add solutions
    for (let i = 0; i < solutions.length; i++) {
      await prisma.projectSolution.create({
        data: {
          text: solutions[i],
          order: i,
          projectId: createdProject.id,
        },
      });
    }

    // Add results
    for (let i = 0; i < results.length; i++) {
      await prisma.projectResult.create({
        data: {
          text: results[i],
          order: i,
          projectId: createdProject.id,
        },
      });
    }

    console.log(`✅ Project: ${project.title}`);
  }

  console.log("🎉 All portfolio projects added!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
